### ISSUE TITLE
请教下 使用这个包如何区分节假日和普通的周末呢

### ISSUE THREAD

**Issue by hafung** [zjkal/time-helper#9]
如上

**Comment by zjkal** [comment]
//判断指定时间是否为周末(周六和周日)
TimeHelper::isWeekend();

//判断指定日期是否为国内的节假日
ChinaHoliday::isHoliday();

**Comment by zjkal** [comment]
如果当天又是节日, 同时又是周六日, 则无法区分.

**Comment by zjkal** [comment]
这个包的节假日数据, 没有做节日和假日的区分, 所以无法满足你的需求

**Comment by zjkal** [comment]
是的，这个函数只是笼统的判断是否是国内的节假日，换句话说就是休息的日子。并不能区分是节日，还是假日。

**Comment by hhrensheng** [comment]
> 是的，这个函数只是笼统的判断是否是国内的节假日，换句话说就是休息的日子。并不能区分是节日，还是假日。

如果不麻烦建议增加一下这个功能

**Comment by zjkal** [comment]
这个需求确实搞不定, 因为节假日数据源头就没有做节日和假日的区分.

**Comment by zjkal** [comment]
如果仅仅判断工作日和周六日可以使用`isWeekday()`和`isWeekend()`

**Comment by hhrensheng** [comment]
> 如果仅仅判断工作日和周六日可以使用`isWeekday()`和`isWeekend()`

好的，主要是想区分普通的周末和节日

**Comment by zjkal** [comment]
> > 如果仅仅判断工作日和周六日可以使用`isWeekday()`和`isWeekend()`
> 
> 好的，主要是想区分普通的周末和节日

从目前的数据源来看, 确实无法区分.我会考虑有没有更好的办法, 可以实现这个需求.
